---
- hosts: all
  tasks:
    - name: update
      command: /sbin/apk update
    - name: Add testing repo
      lineinfile: dest=/etc/apk/repositories line="@testing http://nl.alpinelinux.org/alpine/edge/testing"
    - name: Add edge repo
      lineinfile: dest=/etc/apk/repositories line="@edge http://nl.alpinelinux.org/alpine/edge/main"
