version: '2'
services:
  app:
    image: danh/app
    ports:
      - "3000:3000"
    volumes:
      - ../src:/var/www/app
    links:
      - db
    tty: true
  db:
    image: danh/db
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    tty: true
