---
- hosts: all
  tasks:
    - name: Install node
      apk: name=nodejs
    - name: npm Install
      command: npm install
      args:
        chdir: /var/www/app
    - name: Install consul
      apk: name=consul@testing
    - name: Copy configuration files
      copy: src=./root/etc dest=/
