---
- hosts: all
  tasks:
    - name: Install node
      command: /sbin/apk add nodejs
    - name: npm Install
      command: npm install
      args:
        chdir: /var/www/app
    - name: Copy configuration files
      copy: src=./root/etc dest=/
